### ISSUE TITLE
[OPS-111] 사용자 보유 식재료 추가 API 개발

### ISSUE THREAD

**Issue by hoonww** [SWM13-dazaram/Eureka-Backend#11]
API 명세는 [postman](https://documenter.getpostman.com/view/17474047/UzJQpE1y#bcf6f31a-4c74-4e9d-9558-9bea2626d06a) 참고

## 개발할 API 목록
- findAllIngredientsByCategoryId
- getSelectedIngredientInfo
- setSelectedIngredient
- createCustomIngredient
- createUserIngredient

**Comment by Mo0nl19ht** [comment]
이거 이슈 여러개로 나누는게 좋을듯

**Comment by hoonww** [comment]
이거 댓글달면 알림이 갈지 모르겠는데 일단 작성

규모가 적당해서 나누지 않아도 될것같은데 그래도 나눌까요?
